version: '3.8'

services:
    sakilaapp:
        image: sakilaapp:latest
        ports:
            - '8081:8080'
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=sakila;Username=postgres;Password=postgres
            - ConnectionStrings__IdentityConnection=Host=postgres;Port=5432;Database=sakiladb;Username=postgres;Password=postgres
            - Authentication__Google__ClientId=dummy
            - Authentication__Google__ClientSecret=dummy
            - EmailSettings__SmtpServer=smtp.gmail.com
            - EmailSettings__SmtpPort=587
            - EmailSettings__SenderName=SakilaApp
            - EmailSettings__SenderEmail=dummy@gmail.com
            - EmailSettings__Password=dummy
            - PayPhone__Token=dummy
            - PayPhone__StoreId=dummy
            - PayPal__ClientId=dummy
            - PayPal__ClientSecret=dummy
            - PayPal__BaseUrl=https://api-m.sandbox.paypal.com
            - PayPal__ReturnUrl=http://localhost:8081/Payment/Success
            - PayPal__CancelUrl=http://localhost:8081/Payment/Cancel
        depends_on:
            - postgres
        networks:
            - sakila-default-net
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s

    postgres:
        image: postgres:17
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sakiladb
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./database/init-sakila.sh:/docker-entrypoint-initdb.d/init-sakila.sh
            - ./database/sakila_backup.sql:/docker-entrypoint-initdb.d/sakila_backup.sql
        ports:
            - '5433:5432'
        networks:
            - sakila-default-net
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
            resources:
                limits:
                    memory: 512M

volumes:
    pgdata:
        driver: local

networks:
    sakila-default-net:
        driver: overlay
        ipam:
            config:
                - subnet: 10.200.0.0/24
